### ISSUE TITLE
Provide support to execute only the scenario scripts

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#311] opened 2018-01-05 13:43 UTC
**Description:**
When exposing TestGrid to external customers, they may have the need to get their existing deployment (say, a pre-prod environment) verified against the WSO2 TestGrid. This gives the customers the confidence that whatever they have built is solid.

To make this happen, following should happen:
* Customer provide WSO2 with a list of endpoints and credentials.
* TestGrid will feed this information to Scenarios test scripts, and execute them.
* Scenario test scripts will provide the test results to TestGrid in csv format.
* TestGrid will generate a detailed report about the test status, and email the customer.

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by harshanL** [comment] 2018-02-27 07:44
This is a duplicate of #493

**Closed** 2018-02-27 07:43 UTC
Labels: Priority/Highest, Severity/Critical, Type/New Feature
