### ISSUE TITLE
Working directory of shell scripts should be the job workspace dir

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#478] opened 2018-02-12 09:09 UTC
**Description:**
Currently, the shell scripts set the TESTGRID_HOME as the working directory. This is an issue since the shell scripts of testgrid jobs such as infra-provision.sh will look for artifacts under the TESTGRID_HOME then. 

For example, the local-is-deployment looks for the wso2is-5.4.0.zip distribution under TESTGRID_HOME!
https://github.com/wso2/testgrid/blob/e86b2f1a05ad523f585711f6dbd27bb6327ec3ba/test-scripts/local-is-deployment/Deployment/deploy.sh#L35

We set the working dir at this location:
https://github.com/wso2/testgrid/blob/e86b2f1a05ad523f585711f6dbd27bb6327ec3ba/deployment/src/main/java/org/wso2/testgrid/deployment/deployers/ShellDeployer.java#L52

**Affected Product Version:**
0.9.0-m12

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
See above.

**Related Issues:**
N/A

**Comment by pasindujw** [comment] 2019-03-22 09:27
@DarthFloopy Apologies for missing your comment.
The issue is fixed now. Hence closing.

**Closed by pasindujw** 2019-03-22 09:27 UTC
Labels: Priority/Highest, Severity/Critical, Type/Bug, good first issue
