### ISSUE TITLE
Investigate why Playground2 and PassiveSTSSampleApp web apps not getting deployed

### ISSUE THREAD

**Issue by harshanL** [wso2/testgrid#755] opened 2018-05-10 13:57 UTC
**Description:**

Playground2 and PassiveSTSSampleApp web apps are not deploying in tomcat when running IS scenario tests in TestGrid prod. There are many test-case failures due to this issue. We need to investigate why those apps are not getting deployed. According to the QA-Tomcat instance tomcat logs, travelocity & avis webapps are successfully deployed. But there is no sign of a failure for Playground2 and PassiveSTSSampleApp web apps.

**Affected Product Version:**
0.9.0-m26

**Comment by pasindujw** [comment] 2018-05-25 04:59
@charithag , @kasunbg , @harshanL 
Tried to upload playground app from local machine to the instance where tomcat is deployed using a curl command similar to identity-test-integration scripts, but it is failing due to connection timeout.
With recent security improvement in tomcat instance, I think the curl has to be updated as to use the relevant certificate with it.
Will check further.

**Comment by pasindujw** [comment] 2018-05-31 10:43
Hi all,
The above suspect was wrong and I was able to do Curl from both localhost and TestGrid Home instance successfully to QA-Tomcat instance and deploy playground2 app.

Then from TestGrid Prod, I've triggered a build for WSO2 IS 5.4.1 - LTS and observed the log relates to a scenario where playground2 app is supposed to be deployed.
The log reveals that it is being successfully deployed.
Please refer the log:
([basesetup.log](https://gist.github.com/pasindujw/10153d06bce1c3edde93ecf70450ba0e) of scenario01/jmeter))
```
 [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ playground2 ---
[INFO] Installing /testgrid/testgrid-home/jobs/wso2is-5.4.1-LTS/workspace/identity-test-integration/scenario01/temp/playground2/target/playground2.war to /home/ubuntu/.m2/repository/org/wso2/is/playground2/5.5.0/playground2-5.5.0.war
[INFO] Installing /testgrid/testgrid-home/jobs/wso2is-5.4.1-LTS/workspace/identity-test-integration/scenario01/temp/playground2/pom.xml to /home/ubuntu/.m2/repository/org/wso2/is/playground2/5.5.0/playground2-5.5.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.739 s
[INFO] Finished at: 2018-05-31T10:09:26+00:00
[INFO] Final Memory: 38M/545M
[INFO] ------------------------------------------------------------------------
OK - Deployed application at context path /playground2
OK - Deployed application at context path /travelocity.com
```
Please refer the JenkinsLog = https://testgrid-live.private.wso2.com/admin/job/wso2is-5.4.1-LTS/32/console
Search term:  **playground2** and you will find logs of successfully undeployment of the app as
`OK - Undeployed application at context path /playground2`
(log about deployment is not included in jenkins log, but it is in basesetup.log in above)


However one previous build of the same job had mentioned that playground2 app is Fail at undeployment.
https://testgrid-live.private.wso2.com/admin/job/wso2is-5.4.1-LTS/31/consoleFull
```
[main] INFO org.wso2.testgrid.common.util.TestGridUtil - Execution result : working directory : /testgrid/testgrid-home/jobs/wso2is-5.4.1-LTS/workspace/identity-test-integration/scenario01/jmeter
OK - Undeployed application at context path /travelocity.com
FAIL - No context exists named /playground2
post-steps are done...
```
Since the issue is not observable with the latest builds, we can close the issue.

**Comment by pasindujw** [comment] 2018-05-31 10:56
You can also refer the TestGrid dashboard link : https://testgrid-live.private.wso2.com/wso2is-5.4.1-LTS/is-single-node-deployment/test-plans/1bc2571e-72be-42c2-bd7e-c465233924e2#Single%20Sign%20On%20between%20a%20legacy%20web%20app,%20which%20cannot%20change%20the%20user%20interface%20and%20service%20providers,%20which%20support%20standard%20SSO%20protocols

![up](https://user-images.githubusercontent.com/8229975/40778502-ff32318c-64ee-11e8-86d3-a2e3b8657521.png)

The passing 2 scenarios (scenario01 and scenario22) are using Playground2 apps and which means the app is successfully deploying.

**Comment by lasanthaDLPDS** [comment] 2018-05-31 11:34
As per above comments close the issue.

**Closed by lasanthaDLPDS** 2018-05-31 11:34 UTC
Labels: Priority/Highest, Severity/Critical, Status/In Progress, Type/Task
